name: Automated Git Workflow used by developers

on:
  push:
    branches: ['*']
  pull_request:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  format-code-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Run Black (format instead of check)
        uses: psf/black@stable
        with:
          options: "."

      - name: Run isort (apply changes)
        uses: isort/isort-action@v1
        with:
          requirements-files: ""
          sort-paths: "."
          configuration: "--profile black"

      - name: Check for formatting changes
        id: check-changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Formatting changes were needed and have been applied"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No formatting changes needed"
          fi

      - name: Commit changes back to branch
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git pull
          git add .
          git commit -m "Apply automatic formatting with Black and isort"
          git remote set-url origin https://github.com/${{ github.repository_owner }}/checksum_scripts.git
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Check if PR exists
        id: check-pr
        if: github.event_name == 'push'
        run: |
            BRANCH_NAME="${{ github.ref_name }}"

            # Check if a PR already exists from your forked branch to the main branch of the upstream repository
            PR_EXISTS=$(gh pr list --repo bfidatadigipres/checksum_scripts --head "${{ github.repository_owner }}:$BRANCH_NAME" --base main --json number --jq 'length')

            if [ "$PR_EXISTS" -gt 0 ]; then
              echo "PR for branch $BRANCH_NAME already exists"
              echo "create_pr=false" >> $GITHUB_OUTPUT
            else
              echo "No PR exists for branch $BRANCH_NAME, creating the PR"
              echo "create_pr=true" >> $GITHUB_OUTPUT
            fi
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR
        if: steps.check-pr.outputs.create_pr == 'true' && github.ref != 'refs/heads/main'
        run: |
            echo "Creating PR..."
            gh pr create \
              --repo bfidatadigipres/checksum_scripts \
              --base main \
              --head "${{ github.repository_owner }}:${{ github.ref_name }}" \
              --title "Automated PR from ${{ github.repository_owner }}:${{ github.ref_name }}" \
              --body "This PR was automatically created from forked repo changes."
        env:
            GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Skip PR Creation if Exists
        if: steps.check-pr.outputs.create_pr == 'false'
        run: |
            echo "Skipping PR creation because it already exists."
